const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "",  //  SUHAIL_14_12_05_04_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTA0LFxuICAgICAgICAxNjIsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMTY2LFxuICAgICAgICAzNCxcbiAgICAgICAgMjI3LFxuICAgICAgICAxNDYsXG4gICAgICAgIDMyLFxuICAgICAgICAyNTIsXG4gICAgICAgIDE2NyxcbiAgICAgICAgNjIsXG4gICAgICAgIDE4LFxuICAgICAgICA4NixcbiAgICAgICAgODgsXG4gICAgICAgIDk3LFxuICAgICAgICA4NCxcbiAgICAgICAgODEsXG4gICAgICAgIDIyOCxcbiAgICAgICAgOTEsXG4gICAgICAgIDgyLFxuICAgICAgICA5OCxcbiAgICAgICAgMjAxLFxuICAgICAgICAxNSxcbiAgICAgICAgNjYsXG4gICAgICAgIDIxOCxcbiAgICAgICAgMTIwLFxuICAgICAgICAxMTIsXG4gICAgICAgIDYwLFxuICAgICAgICAyLFxuICAgICAgICAxNjcsXG4gICAgICAgIDE2NSxcbiAgICAgICAgOTFcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMzgsXG4gICAgICAgIDk0LFxuICAgICAgICAxNTEsXG4gICAgICAgIDE3NyxcbiAgICAgICAgMTE0LFxuICAgICAgICAxNjksXG4gICAgICAgIDExMyxcbiAgICAgICAgMTMsXG4gICAgICAgIDUyLFxuICAgICAgICAxMjksXG4gICAgICAgIDMxLFxuICAgICAgICA4NixcbiAgICAgICAgMTM2LFxuICAgICAgICAyNTQsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMjU0LFxuICAgICAgICAxMzQsXG4gICAgICAgIDE2MixcbiAgICAgICAgMTEzLFxuICAgICAgICAyMDQsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMTQzLFxuICAgICAgICAyMjcsXG4gICAgICAgIDYwLFxuICAgICAgICAyMTksXG4gICAgICAgIDIyNSxcbiAgICAgICAgNjEsXG4gICAgICAgIDIwLFxuICAgICAgICAxODMsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMjI5LFxuICAgICAgICAyNlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjA4LFxuICAgICAgICAxMzYsXG4gICAgICAgIDg5LFxuICAgICAgICA2NixcbiAgICAgICAgMTYyLFxuICAgICAgICAxMjMsXG4gICAgICAgIDIwMixcbiAgICAgICAgNDIsXG4gICAgICAgIDE2NixcbiAgICAgICAgOTgsXG4gICAgICAgIDIxLFxuICAgICAgICAxNTksXG4gICAgICAgIDYsXG4gICAgICAgIDIyOCxcbiAgICAgICAgNCxcbiAgICAgICAgMTE1LFxuICAgICAgICA4NixcbiAgICAgICAgMTY2LFxuICAgICAgICAxNjEsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMTY3LFxuICAgICAgICAyMCxcbiAgICAgICAgMTE1LFxuICAgICAgICAyMTUsXG4gICAgICAgIDMxLFxuICAgICAgICAxMDIsXG4gICAgICAgIDE1N
  errorChat : process.env.ERROR_CHAT || "",CxcbiAgICAgICAgOTgsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMTM2LFxuICAgICAgICAxMSxcbiAgICAgICAgOThcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMzgsXG4gICAgICAgIDE0MCxcbiAgICAgICAgODIsXG4gICAgICAgIDc3LFxuICAgICAgICAxODQsXG4gICAgICAgIDQ3LFxuICAgICAgICA2MyxcbiAgICAgICAgMzMsXG4gICAgICAgIDE0MixcbiAgICAgICAgMTI1LFxuICAgICAgICA5NixcbiAgICAgICAgMjM1LFxuICAgICAgICA5OSxcbiAgICAgICAgMTk2LFxuICAgICAgICAyMDUsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTA1LFxuICAgICAgICAyNTMsXG4gICAgICAgIDIxNyxcbiAgICAgICAgMTExLFxuICAgICAgICAyNDAsXG4gICAgICAgIDkxLFxuICAgICAgICAxNixcbiAgICAgICAgMTUyLFxuICAgICAgICA4MyxcbiAgICAgICAgMTkzLFxuICAgICAgICAxOSxcbiAgICAgICAgMixcbiAgICAgICAgMTksXG4gICAgICAgIDEyMSxcbiAgICAgICAgMTMwLFxuICAgICAgICAyNFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjQsXG4gICAgICAgIDgxLFxuICAgICAgICAyMDMsXG4gICAgICAgIDI0NixcbiAgICAgICAgMTIzLFxuICAgICAgICAyMDEsXG4gICAgICAgIDE1LFxuICAgICAgICAyMTIsXG4gICAgICAgIDE0OCxcbiAgICAgICAgOSxcbiAgICAgICAgODksXG4gICAgICAgIDY1LFxuICAgICAgICAyNDQsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMTQ4LFxuICAgICAgICAxNjQsXG4gICAgICAgIDQ3LFxuICAgICAgICAyMjMsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMixcbiAgICAgICAgMjU0LFxuICAgICAgICAxOCxcbiAgICAgICAgODUsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMjIxLFxuICAgICAgICA0NixcbiAgICAgICAgMTg3LFxuICAgICAgICA2NSxcbiAgICAgICAgMTcsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMjMwLFxuICAgICAgICA5MFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA1OSxcbiAgICAgICAgMTg4LFxuICAgICAgICAzNyxcbiAgICAgICAgNzgsXG4gICAgICAgIDQxLFxuICAgICAgICAyNDgsXG4gICAgICAgIDIwMSxcbiAgICAgICAgMTc5LFxuICAgICAgICA5NyxcbiAgICAgICAgODksXG4gICAgICAgIDUyLFxuICAgICAgICAyMDUsXG4gICAgICAgIDY1LFxuICAgICAgICA4LFxuICAgICAgICA0MyxcbiAgICAgICAgMTUxLFxuICAgICAgICA2NCxcbiAgICAgICAgMjQsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMjI4LFxuICAgICAgICAxNTEsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMjA0LFxuICAgICAgICAxMzYsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMTgwLFxuICAgICAgICAyMzMsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMTk1LFxuICAgICAgICA2NSxcbiAgICAgICAgMTYyLFxuICAgICAgICAxOVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgMTQxLFxuICAgICAgICAgIDUwLFxuICAgICAgICAgIDE5MSxcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgMjE3LFxuICAgICAgICAgIDIxMixcbiAgICAgICAgICA4OCxcbiAgICAgICAgICA2LFxuICAgICAgICAgIDE4MCxcbiAgICAgICAgICAxMCxcbiAgICAgICAgICAxOTcsXG4gICAgICAgICAgMTYyLFxuICAgICAgICAgIDEwMixcbiAgICAgICAgICAyLFxuICAgICAgICAgIDQ2LFxuICAgICAgICAgIDIxOSxcbiAgICAgICAgICAwLFxuICAgICAgICAgIDE4MSxcbiAgICAgICAgICAxNDQsXG4gICAgICAgICAgNDYsXG4gICAgICAgICAgNzUsXG4gICAgICAgICAgNDksXG4gICAgICAgICAgMjUzLFxuICAgICAgICAgIDMwLFxuICAgICAgICAgIDM0LFxuICAgICAgICAgIDE1MixcbiAgICAgICAgICAyMCxcbiAgICAgICAgICA5LFxuICAgICAgICAgIDI1NCxcbiAgICAgICAgICAxODMsXG4gICAgICAgICAgODVcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTYyLFxuICAgICAgICAgIDE5MyxcbiAgICAgICAgICAxNjMsXG4gICAgICAgICAgMjI0LFxuICAgICAgICAgIDI1MCxcbiAgICAgICAgICAxOTEsXG4gICAgICAgICAgMTE0LFxuICAgICAgICAgIDIxMyxcbiAgICAgICAgICAxNCxcbiAgICAgICAgICAyLFxuICAgICAgICAgIDk0LFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICAyMjIsXG4gICAgICAgICAgMjM0LFxuICAgICAgICAgIDE2MixcbiAgICAgICAgICAxNzAsXG4gICAgICAgICAgMTU0LFxuICAgICAgICAgIDExNCxcbiAgICAgICAgICAzMyxcbiAgICAgICAgICAxNzUsXG4gICAgICAgICAgMTA5LFxuICAgICAgICAgIDE1NSxcbiAgICAgICAgICAyMTMsXG4gICAgICAgICAgMTU0LFxuICAgICAgICAgIDIzNCxcbiAgICAgICAgICA4MyxcbiAgICAgICAgICA2NixcbiAgICAgICAgICA5MCxcbiAgICAgICAgICAxNTUsXG4gICAgICAgICAgODAsXG4gICAgICAgICAgMTIwLFxuICAgICAgICAgIDYxXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNTIsXG4gICAgICAgIDIwOCxcbiAgICAgICAgMTA0LFxuICAgICAgICAyNDksXG4gICAgICAgIDQ5LFxuICAgICAgICA5MSxcbiAgICAgICAgMTU5LFxuICAgICAgICAxMTIsXG4gICAgICAgIDE2NyxcbiAgICAgICAgNzMsXG4gICAgICAgIDIsXG4gICAgICAgIDM2LFxuICAgICAgICAyMjgsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTUyLFxuICAgICAgICA3MyxcbiAgICAgICAgOSxcbiAgICAgICAgMjQsXG4gICAgICAgIDIxNyxcbiAgICAgICAgMjUwLFxuICAgICAgICAyNDgsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMTIzLFxuICAgICAgICAxNTksXG4gICAgICAgIDQxLFxuICAgICAgICA4OCxcbiAgICAgICAgMTksXG4gICAgICAgIDQ1LFxuICAgICAgICAzOCxcbiAgICAgICAgMTMzLFxuICAgICAgICAxMjEsXG4gICAgICAgIDE5LFxuICAgICAgICA2NCxcbiAgICAgICAgMSxcbiAgICAgICAgNTcsXG4gICAgICAgIDkyLFxuICAgICAgICAxNjksXG4gICAgICAgIDU4LFxuICAgICAgICAxNDksXG4gICAgICAgIDIzMCxcbiAgICAgICAgMTc3LFxuICAgICAgICAxLFxuICAgICAgICA0MyxcbiAgICAgICAgMjIzLFxuICAgICAgICA3NyxcbiAgICAgICAgMjQwLFxuICAgICAgICA3NCxcbiAgICAgICAgMjI1LFxuICAgICAgICAyNyxcbiAgICAgICAgMTI3LFxuICAgICAgICAxNTgsXG4gICAgICAgIDIxNixcbiAgICAgICAgMTA1LFxuICAgICAgICA0NyxcbiAgICAgICAgMTY4LFxuICAgICAgICAyMTgsXG4gICAgICAgIDIyMixcbiAgICAgICAgMjYsXG4gICAgICAgIDgxLFxuICAgICAgICA5MixcbiAgICAgICAgMjQ3LFxuICAgICAgICA5MSxcbiAgICAgICAgMTI2LFxuICAgICAgICAxMzJcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDEwOCxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCIreDA0bUhIcFB4TkdWMVorVjZBYXF5ODRFaThrei9pREZzclFOR2Q3ZWNBPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjk0NzczODk0NzI0QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCIzOTlBMDgyMTY3QkFBMEY1NjMzQTdFMDZBMzJCRTY4NVwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3NDYzNjc5MjZcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5NDc3Mzg5NDcyNEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiQTJBOEU2RUZGRjE3MTI0QzRFNDMyOEEyRERFMjQ4RjJcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzQ2MzY3OTI2XG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMSxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcIkFuN2JSalU3U0dPOXFnOWNxX3BQV0FcIixcbiAgXCJwaG9uZUlkXCI6IFwiMDgxOTY0MjUtZmI2OC00ZjU4LWE4ZDItODVhODZjN2UzZDVjXCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDc0LFxuICAgICAgNyxcbiAgICAgIDM3LFxuICAgICAgMTYsXG4gICAgICA2NixcbiAgICAgIDE5NSxcbiAgICAgIDQ4LFxuICAgICAgMTMsXG4gICAgICA1MSxcbiAgICAgIDE2MSxcbiAgICAgIDE3MyxcbiAgICAgIDI4LFxuICAgICAgMjIxLFxuICAgICAgMTQ0LFxuICAgICAgODgsXG4gICAgICAxMTIsXG4gICAgICAxODksXG4gICAgICAxODAsXG4gICAgICA3MyxcbiAgICAgIDI1NVxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA1NyxcbiAgICAgIDg5LFxuICAgICAgMTU4LFxuICAgICAgMTcsXG4gICAgICAyMTgsXG4gICAgICAxNjEsXG4gICAgICA5NCxcbiAgICAgIDEyNCxcbiAgICAgIDQxLFxuICAgICAgMTM1LFxuICAgICAgMTAzLFxuICAgICAgMTYwLFxuICAgICAgODQsXG4gICAgICAxOTIsXG4gICAgICAxOTQsXG4gICAgICAxMTMsXG4gICAgICA4OCxcbiAgICAgIDIxNyxcbiAgICAgIDE5LFxuICAgICAgNjlcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiUFBTMUc5SjdcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjk0NzczODk0NzI0OjVAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcIm5hbWVcIjogXCJEaW51a2EgYm90XCIsXG4gICAgXCJsaWRcIjogXCIyMDg3MjMyMTM1OTQ4MzE6NUBsaWRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNON0sxN2tFRUsvcjNjQUdHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIjZMeEZQdisyUmFDdVNQbXpaQ3ZkZnlFTG9wSHNHVkxEQno4N09FVGQ4bjA9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiQWsrRXdUamwvRFlNVUxyeWZnczZGempZQkh0cGhKc0Vqb2xEVXUzT01PdFlHQ1k4Ry9LOGVidGM3UlRwbU9TMC9nK3Ivb3MzQUlxNllZdEMwaDRVRGc9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiMmxKSXZyTHVKdFBjaU9jM25RUHRvbzdZL0hFWnYxZmpEcWt5TFB1eUlPS1lWanpiWVEzenIvZWNYVkNrUGlIMnJQaHBveVN4MkFrWGc1MW4wcHFjZ0E9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiOTQ3NzM4OTQ3MjQ6NUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDIzMixcbiAgICAgICAgICAxODgsXG4gICAgICAgICAgNjksXG4gICAgICAgICAgNjIsXG4gICAgICAgICAgMjU1LFxuICAgICAgICAgIDE4MixcbiAgICAgICAgICA2OSxcbiAgICAgICAgICAxNjAsXG4gICAgICAgICAgMTc0LFxuICAgICAgICAgIDcyLFxuICAgICAgICAgIDI0OSxcbiAgICAgICAgICAxNzksXG4gICAgICAgICAgMTAwLFxuICAgICAgICAgIDQzLFxuICAgICAgICAgIDIyMSxcbiAgICAgICAgICAxMjcsXG4gICAgICAgICAgMzMsXG4gICAgICAgICAgMTEsXG4gICAgICAgICAgMTYyLFxuICAgICAgICAgIDE0NSxcbiAgICAgICAgICAyMzYsXG4gICAgICAgICAgMjUsXG4gICAgICAgICAgODIsXG4gICAgICAgICAgMTk1LFxuICAgICAgICAgIDcsXG4gICAgICAgICAgNjMsXG4gICAgICAgICAgNTksXG4gICAgICAgICAgNTYsXG4gICAgICAgICAgNjgsXG4gICAgICAgICAgMjIxLFxuICAgICAgICAgIDI0MixcbiAgICAgICAgICAxMjVcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcInNtYmFcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTc0NjM2NzkyMyxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQUJTMVwiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBQlMxLmpzb24iOiAie1wia2V5RGF0YVwiOlwiTVNMelBKT2NRczNFUDZiN3JnK1BJT013QUZzbHNlcDZFSW5CMVJ4T1dyWT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMTk0NzE0NDYyLFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3NDYzNjc5MjU2NTZcIn0iCn0=
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
